sudo: required

language: python

services:
    - docker

before_script:
    - docker-compose -f db/docker-compose.yml build
    - docker-compose -f db/docker-compose.yml up &
    - pip install tavern[pytest]

script:
    - py.test db/*.tavern.yaml
