sudo: required

language: python

services:
    - docker

before_install:
    - docker-compose -f db/docker-compose.yml build
    - docker-compose -f db/docker-compose.yml up &

script:
    - pytest db/*.tavern.yml
