# docker-compose.yml

version: '3'
services:
  jointpay-db-api:
    image: postgrest/postgrest
    ports:
      - "3000:3000"
    links:
      - jointpay-db:db
    environment:
      PGRST_DB_URI: postgres://app_user:password@db:5432/app_db
      PGRST_DB_SCHEMA: jointpay
      PGRST_DB_ANON_ROLE: app_user #In production this role should not be the same as the one used for the connection
    depends_on:
      - jointpay-db
  jointpay-db:
    build: .
    image: jointpay-db
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: password
  # Uncomment this if you want to persist the data.
  # volumes:
  #   - "./pgdata:/var/lib/postgresql/data"
  jointpay-db-swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    expose:
      - "8080"
    links:
      - jointpay-db-api:api
    environment:
      API_URL: http://localhost:3000/
